algolia/docsearch-scraper

deployer/deploy
scraper/deployer/fetchers.py
scraper/deployer/index.py

Launch deployer as a module for relative imports

---

README.md

Fix link to Algolia account in README

---

scraper/src/algolia_helper.py
scraper/src/config/config_loader.py
scraper/src/config/config_validator.py
scraper/src/documentation_spider.py
scraper/src/tests/config_loader/basic_test.py

add Sitemap feature: add ability to crawl though a sitemap.xml

---

.gitignore

This is a teeny quality of life improvement (for me mostly, but maybe others?).

ignore envS

---

README.md
deployer/src/snippeter.py
playground/index.html

refactor(CDN)Update CDN URL such as jsDelivr new standard

---

scraper/src/config/browser_handler.py
scraper/src/custom_downloader_middleware.py
scraper/src/index.py

refactor(custom_middleware) Enhance naming precision of the middleware used

---

deployer/src/config_manager.py
deployer/src/emails.py
deployer/src/index.py

fix missing private repo
fix typos
fix unicode & configuration issue
avoid miss matching type issue
We still use tmp folder since you may have other edited files not tracked (pending config) from your PUBLIC_CONFIG_FOLDER

fix errors #373

---

cli/src/commands/bootstrap_config.py
deployer/src/config_creator.py

introduce a new parameter : `sitemap_alternate_links` for Docusaurus's set up > 1.3.2
algolia/docsearch-scraper#387
Ordering key in a more relevant way
Enhance root detection for pkgdown set up

[bootstrap] Introduce sitemap_alternate_links

---

requirements.txt
scraper/src/documentation_spider.py

Issue:
Alternative links were not crawled in production after #387 since Scrapy was not updated in the docker environment
Updating scrapy to take advantage of scrapy/scrapy#2854

Fix(sitemap_crawling) refactor(spider) Ficing crawl for every kind of url

---

deployer/src/snippeter.py

This changes the link in the snippet about styling to go directly to the styling page.

Change link to styling guide

---

deployer/src/config_creator.py
deployer/src/helpdesk_helper.py

Since we have received several application [from larecipe](https://larecipe.binarytorch.com.my/docs/1.2/overview), let's make it a truth integration.
This PR do also some minor fixes:
- remove unused step (variable)
- avoid having `lvl5` after `text`

[Bootstrap] Generate larecipe template

---

CHANGELOG.md
deployer/src/config_creator.py

Fix sitemap from URL

---

deployer/src/config_creator.py

updating template for pkgdown website to use their UI integration r-lib/pkgdown#639 #397

[Bootstrap] Adapt our template for pkgdown website to match their custom UI needs

---

deployer/src/config_creator.py
deployer/src/helpdesk_helper.py
deployer/src/snippeter.py

This PR impacts only the bootstrap tooling. It has no impact over the crawler
- Use new tags introduced by the hub
- Bootstrap [publii generator](https://getpublii.com/dev/)

[bootstrap] Update tags from helpscout

---

cli/src/commands/disable_connector.py
cli/src/commands/enable_connector.py
cli/src/commands/reindex_connector.py
deployer/src/algolia_internal_api.py
deployer/src/config_creator.py
deployer/src/fetchers.py
deployer/src/helpdesk_helper.py
deployer/src/helpers.py
scraper/src/algolia_helper.py
scraper/src/config/nb_hits_updater.py
scraper/src/index.py
scraper/src/strategies/default_strategy.py

This PR enhance the global style of the codebase

Style prepare codebase's style to python 3

---

deployer/src/config_manager.py
deployer/src/helpers.py
deployer/src/index.py

Fixes how we handle string from the deployer

Deployer: Fix string management

---

Pipfile
Pipfile.lock
README.md
cli/src/commands/bootstrap_config.py
cli/src/commands/deploy_configs.py
deployer/src/algolia_helper.py
deployer/src/config_creator.py
deployer/src/config_manager.py
deployer/src/snippeter.py
scraper/src/config/config_loader.py
scraper/src/config/urls_parser.py
scraper/src/custom_downloader_middleware.py
scraper/src/documentation_spider.py
scraper/src/strategies/default_strategy.py

The commits in there are completely related to Python3 - they would probably break in Python2, either from a behavioural point of view or from a performance one.
We will now support python 3

Migrate to Python3

---

Pipfile
Pipfile.lock
scraper/dev/docker/Dockerfile.base

This PR:
- Update the chrome version being used. Use the latest 74
- Update the correct version of python being used (3.6)
resolves #456

Fix/feat(chrome) Use latest chrome version 74

---

Pipfile.lock

(we must setup an automatic check on Pipfile.lock, so that it does not drift away when Pipfile is updated!)

Pipefile.lock: Regenerate from Pipfile

---

.pylintrc
cli/src/commands/abstract_command.py
deployer/src/algolia_internal_api.py
deployer/src/config_creator.py
deployer/src/index.py
deployer/src/snippeter.py
scraper/src/config/urls_parser.py
scraper/src/custom_downloader_middleware.py
scraper/src/custom_dupefilter.py
scraper/src/documentation_spider.py
scraper/src/tests/config_loader/open_selenium_browser_test.py
scraper/src/tests/default_strategy/xpath_test.py

As unnecessary now that the switch to Python3 is complete.

all: Stop recovering import urllib.parse

---

deployer/src/algolia_helper.py
deployer/src/snippeter.py

Issue: Facets were not correctly retrieved and some muted errors happened.
Now the snippet is correctly build depending on the facets available

Snippeter fix facet

---

.env.example
CONTRIBUTING.md
scraper/src/documentation_spider.py
scraper/src/index.py

Last attempt of https://github.com/algolia/docsearch-scraper/pull/486 :-) 
Now confirmed to be actually working! 🎉 
I've added a warning so users won't randomly send tokens to 3rd party sites.

Fix IAP / CF Access authentication

---

CONTRIBUTING.md

doc(contributing): make explicit changes introduces by #481, follow up on #498

doc(contributing): support for HTTP basic auth

---

cli/src/commands/bootstrap_config.py

cc https://github.com/algolia/docsearch-configs/commit/fdaee24271b4cc46e049331842277b7e92b83364
DISCLAIMER: This PR does not affect the scraper image, it will not imply a new release.

refactor(cli): remove deprecated config settings

---

scraper/src/strategies/default_strategy.py
scraper/src/tests/default_strategy/default_value_test.py
scraper/src/tests/default_strategy/get_records_from_dom_test.py

This PR is needed to enhance the v3 experience:

feat: avoid indexing element without current_level set

---

CONTRIBUTING.md
README.md
deployer/src/snippeter.py

style: prevent redirections

---

README.md

This PR updates the README to integrate the new repo dedicated to the documentation website.
This PR only impacts the documentation. It will not imply a new release of the scraper

docs(readme): update related projects with website repo

---

deployer/src/index.py
scraper/dev/docker/Dockerfile.base
scraper/src/strategies/algolia_settings.py

Upgrade headless chrome to last stable 85 to fix the docker build

deps: upgrade headless chrome to stable 85

---

deployer/src/config_creator.py

The function will check the `sitemap.xml` endpoint and add it only if it's available.
This leverage checking if a `sitemap.xml` is available

feat: check sitemap status code endpoint to improve config generation

---

deployer/src/config_creator.py

**Summary**
`to_fixme_config`
When the documentation isn't made with a website generator, most of the time, the main content is in an `article` or a `main` tag.
The `FIXME` will be replaced by one of these two if it's available.
`get_sitemap_if_available`
Prevent throwing if the URL isn't well formated (root URL without `/`)
`to_vuepress_config`
Add `get_sitemap_if_available` check to vuepress configs

feat: check if `article` or `main` is available for FIXME configs

---

README.md

Update `README` in order to let the users know why this repo is not maintained anymore.

chore(repo): archive
