scraper/deployer/emails.py

The deploy script now changes directory, this commit adapts to this change
when deploying emails.

Fix updating emails while deploying

---

README.md

Installing `pip` requirements worked better when using the `--user` argument on my system. Otherwise I got permission warning. I think it's safe to add it.
cc @ercolanelli-leo

docs(readme): Adding --user argument to pip

---

.travis.yml
README.md
cli/src/commands/bootstrap_config.py
cli/src/commands/build_docker_scraper.py
cli/src/commands/run_config_docker.py

I've also renamed 2 commands:
- docker:config-run -> docker:run (to match the regular `run` command)
- docker:build-scraper -> docker:build (nicer for non-Algolia employees)
cc @pixelastic @maxiloc @ElPicador

docs(readme): setup documentation readbility & usability improvements

---

README.md

The repo URL is probably pointing to the old repo name.

Update repo URL in README.md

---

.gitignore
README.md

* Provide instructions for running tests with or without docker
* Ignore the pytest cache from all directories
* Ensure the user environnement is not use in the tests

Add instructions for running the tests

---

scraper/src/custom_dupefilter.py
scraper/src/documentation_spider.py

avoid scrapping two time the same page. 
Issue: pages that are directly reachable and redirected were scrapping 2 times

fix(duplicates): pages that are directly reachable and redirected were scrapping 2 times

---

scraper/src/config/config_loader.py
scraper/src/config/config_validator.py
scraper/src/documentation_spider.py

A lot of algolia docsearch users are Docusaurus users. For example: Docusaurus, React Native, Jest, Prettier, Reasonml, Babel and many more.
In Docusaurus, we implement the sitemap for docs with multiple languages according to [google's spec](https://support.google.com/webmasters/answer/189077?hl=en&visit_id=1-636663918916415691-3337098161&rd=1)
According to https://github.com/facebook/Docusaurus/issues/826, algolia docsearch is unable to scrape alternate_url, but this can simply be fixed by enabling `sitemap_alternate_links` since the scraper is based on Scrapy 1.4
https://github.com/algolia/docsearch-scraper/blob/df13ac5d9ff6f684a4d2fb4623625bc05ce3ab5b/requirements.txt#L33
Referring to https://doc.scrapy.org/en/1.4/topics/spiders.html#scrapy.spiders.SitemapSpider.sitemap_alternate_links …

Enable DocSearch to scrape alternate languages in sitemap

---

scraper/src/config/config_loader.py

This user_agent will help sysadmin to identify our crawler.
When `js_render` is not set, out user_agent will be `Algolia DocSearch Crawler`.
When `js_render` is set to true, the user_agent is currently `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/71.0.3578.98 Safari/537.36`
This will partially resolves https://github.com/algolia/docsearch-scraper/issues/404

updating user_agent for crawl made without js_rendering

---

scraper/src/config/config_loader.py
scraper/src/config/nb_hits_updater.py
scraper/src/index.py

resolves #425
To help with naming, I decided to rename the method update_nb_hits to update_nb_hits_property, leaving room for the update_nb_hits config property.
If you'd like to see this done another way, just let me know.

resolves #425 bypass nb_hit_updater if UPDATE_NB_HITS is set or term is not a tty

---

scraper/src/custom_dupefilter.py
scraper/src/documentation_spider.py

It fixes custom_dupefilter way of handling URL

fix: use the right email to create the fingerprint of a page

---

cli/src/commands/abstract_build_docker.py
scraper/dev/docker/Dockerfile.base

This PR deploys the new image using python v3. Changes are here to backup the full v3 porting

Deploy image before porting to python v3

---

deployer/src/helpers.py

Porting to python 3 has been done thanks to several small PRs
This PR is now enhancing the string management.

Strings management: use the newest recommended way to handle literals

---

.env.example
CONTRIBUTING.md
Pipfile
Pipfile.lock
scraper/src/documentation_spider.py

Hey @s-pace ,
We had a use case where we need to scrape site behind Google Identity Aware proxy. I've made a [package for requests](https://github.com/kiwicom/requests-iap) to handle it and I would love to push it to upstream in case someone will have a similar use case.
I had an issue though - After 2 hours, I wasn't able to make `pipenv` work with python3 on my macbook, so I gave up and pushed it without `Pipenv.lock` file. Would it please be possible for you to push .lock file? Another option for me is to push 1 more commit with the upgrade to 3.7.
More details about IAP: https://cloud.google.com/iap/docs/authentication-howto

Add option to scrape sites behind Google Identity Aware Proxy

---

scraper/src/documentation_spider.py

Apologies for the stupid mistake introduced, but https://github.com/kiwicom/requests-iap/blob/master/requests_iap/iapauth.py#L56 expects `r` in the `__call__`. 
This should address the issue.

Fix IAP authentication

---

.dockerignore

The CLI wrap the `docker build` command. Docker context is the root of this project. `.dockerignore` reflects `.gitignore`

docker: add .dockerignore to prevent sharing sensitive data or useless files into the docker image

---

deployer/src/config_creator.py
deployer/src/helpdesk_helper.py

- bootsrap_config: introduces docusaurus v2
- config_creator: update vuepress tempalte
Disclaimer: This PR does not affect the crawler itself. It will not introduces a new release.

config_creator: update vuepress template & docusaurus

---

scraper/dev/docker/Dockerfile.base

This PR:
- use google chrome 78
- enforce the version of `google-chrome-stable` used so that it doesn't depend of the time when we build the docker image which ends up with a fatal error due to an incompatibility between chrome & the driver.
We will release a new version of the scraper that will be pushed to docker HUB.(v1.5.0 and latest)
Closes #478

feat(headless_chrome): use google chrome 78

---

scraper/src/strategies/default_strategy.py
scraper/src/tests/default_strategy/meta_test.py

This change will make sure we do not wrongly truncate number. Issue impacting one of our user.
Example of the issue: 5.20 being truncated into 5.2

feat(meta): do not jsonized version meta

---

scraper/dev/docker/Dockerfile.base

This PR update the headless chrome used to render JS. This is required since apt-get doesn't provide anymore the previous version used. It solves the defective docker build.
Resolves #508

feat: update chrome to 83.0.4103.61

---

deployer/src/config_creator.py

This PR make sure to generate proper config setting for vuepress websites.
This PR only impacts the tooling used by the DocSearch team. It will not imply a new release of the scraper.
Follows algolia/docsearch-scraper#341

generator(vuepress): use correct naming of scrape_start_urls

---

scraper/dev/docker/Dockerfile
scraper/dev/docker/Dockerfile.base
scraper/dev/docker/Dockerfile.dev
scraper/dev/docker/Dockerfile.test

This PR removes deprecated MAINTAINER instructions and use correct case for instruction
This PR only impacts the tooling used by the DocSearch team. It will not imply a new release of the scraper.

refactor(dockerfile): remove deprecated instructions

---

deployer/src/config_creator.py

This PR upgrades the template used to bootstrap configuration for Docusaurus 2
This PR only impacts the tooling used by the DocSearch team. It will not imply a new release of the scraper.

feat(cli): update docusaurus v2 config template to welcome DocSearch v3

---

scraper/src/tests/default_strategy/get_records_from_dom_test.py
scraper/src/tests/default_strategy/meta_test.py
scraper/src/tests/default_strategy/min_indexed_level_test.py
scraper/src/tests/default_strategy/page_rank_test.py
scraper/src/tests/default_strategy/strip_chars_test.py
scraper/src/tests/default_strategy/tags_test.py

This PR removes superfluous selectors overriding from abstract
This PR only impacts the test suite of the scraper. It doesn't bring any new feature. It will not imply a new release of the scraper.

refactor(tests): remove superfluous selectors overriding 

---

scraper/src/tests/default_strategy/get_records_from_dom_test.py

This PR makes sure to test the default strategy. We do not index record when text element is empty.
Resolves #361
This PR only impacts the test suite of the scraper. It doesn't bring any new feature. It will not imply a new release of the scraper.

test: add test on empty text element

---

cli/src/commands/deploy_config.py
deployer/src/index.py

When publishing a config after has been reviewed, since it exists already in the repo, the api key will not be created

fix: add config_exists to the command in order to add a new api key

---

deployer/src/config_creator.py

Update config generator with correct `lvl0` and remove `docs` appended at the end of the `start_url`  for Docusaurus 2 configs

fix docusaurus v2 missing attributesForFaceting and wrong lvl0

---

deployer/src/config_manager.py
deployer/src/helpdesk_helper.py

This PR sends HelpScout snippet in `draft reply` instead of `notes`, which makes the deploy faster as we can directly send from it.

Use draft instead of notes to deploy faster

---

Pipfile
Pipfile.lock
deployer/src/algolia_helper.py
deployer/src/config_manager.py
scraper/src/algolia_helper.py

We were using the python client `1.13`, upgrading it to latest stable (`2.4.0`) allow us to use the `copy_rules` method, which helps users that run on their own as they won't have to re-write their rules or use replicas.
Tested on: generating - running - deploying ~20 configs

upgrade algoliasearch python client from 1.x to 2.x
